### ISSUE TITLE
User Story 13, User can Login

### ISSUE THREAD

**Issue by ryandbarnett** [PhilipDeFraties/monster_shop_2005#13]
As a visitor
When I visit the login path
I see a field to enter my email address and password
When I submit valid information
If I am a regular user, I am redirected to my profile page
If I am a merchant user, I am redirected to my merchant dashboard page
If I am an admin user, I am redirected to my admin dashboard page
And I see a flash message that I am logged in

**Comment by PhilipDeFraties** [comment]
I think the logical order to do things would have been to finish this story first then go back to the earlier stories. The earlier stories can be done first but they each create the functionality necessary for this story whereas completing this first would allow the earlier stories to be completed independently.

**Comment by ryandbarnett** [comment]
Going to keep this open until video review and merge into main.

**Comment by ryandbarnett** [comment]
[Video Review](https://www.loom.com/share/e5da3c3890d8472195206d83f36cd6dd)
