### ISSUE TITLE
Question: Should zip code be an integer or a string?

### ISSUE THREAD

**Issue by ryandbarnett** [PhilipDeFraties/monster_shop_2005#18]
Should zip code be an integer or a string?

Zip code is currently an integer in every table.

We have set it to be a string in our Users table because zip codes that are integers could potentially have their leading zeros removed.

Should we change the other tables zip code to strings?

We decided to go with strings because of potential for leading zeros to be cut off.

**Comment by PhilipDeFraties** [comment]
I doubt its something that would be counted against us to leave them the way they are but if its bothering you I see no harm in changing it, either the table we made (probably the easiest solution) or changing the preexisting tables
