### ISSUE TITLE
User Story 21, User Can Edit their Password

### ISSUE THREAD

**Issue by dhalverson** [PhilipDeFraties/monster_shop_2005#23]
As a registered user
When I visit my profile page
I see a link to edit my password
When I click on the link to edit my password
I see a form with fields for a new password, and a new password confirmation
When I fill in the same password in both fields
And I submit the form
Then I am returned to my profile page
And I see a flash message telling me that my password is updated

**Comment by ryandbarnett** [comment]
[Video Review](https://www.loom.com/share/21ba588a6fad4408820893d3ad55864e)
