### ISSUE TITLE
User Story 27, User Profile displays Orders link

### ISSUE THREAD

**Issue by dhalverson** [PhilipDeFraties/monster_shop_2005#30]
As a registered user
When I visit my Profile page
And I have orders placed in the system
Then I see a link on my profile page called "My Orders"
When I click this link my URI path is "/profile/orders"

**Comment by ryandbarnett** [comment]
My orders link is not appearing.

[Video Review](https://www.loom.com/share/f5ad341044734a5395a30f2c5dbc38c4)

**Comment by ryandbarnett** [comment]
Complete!
[Video Review](https://www.loom.com/share/db9e5c08ad9249bca4468d92fe1b092e)
