### ISSUE TITLE
User Story 28, User Profile displays Orders

### ISSUE THREAD

**Issue by dhalverson** [PhilipDeFraties/monster_shop_2005#31]
As a registered user
When I visit my Profile Orders page, "/profile/orders"
I see every order I've made, which includes the following information:
- the ID of the order, which is a link to the order show page
- the date the order was made
- the date the order was last updated
- the current status of the order
- the total quantity of items in the order
- the grand total of all items for that order

**Comment by ryandbarnett** [comment]
The id of the order is not a link to the show page.

Missing date last updated and total quantity of items in order

User Story 28 doesn't require the vendor name

[Video Review](https://www.loom.com/share/e95c106414ef47078c3c500783f00fee)

**Comment by ryandbarnett** [comment]
[Video Review](https://www.loom.com/share/d5c4175dbbe5472f84d00622ec241baa)
